import { ArrowRight, Baby, BatteryFull, Bell, Cake, Calendar, CalendarCheck, Camera, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Clock, CloudOff, Coffee, CupSoda, FileText, Gift, Globe, History, House, Image, Info, Lock, LogOut, Mail, MapPin, MessageCircle, Minus, Pencil, Percent, Phone, Plus, QrCode, Search, Settings, ShieldAlert, Sparkles, Trash2, TriangleAlert, UserPlus, UserRound, Wifi, X, type LucideIcon } from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  gift: Gift,
  smile: Baby,
  baby: Baby,
  clock: Clock,
  pin: MapPin,
  phone: Phone,
  cake: Cake,
  history: History,
  logout: LogOut,
  trash: Trash2,
  chevron: ChevronRight,
  camera: Camera,
  check: Check,
  bell: Bell,
  house: House,
  qr: QrCode,
  coffee: Coffee,
  user: UserRound,
  "cup-soda": CupSoda,
  percent: Percent,
  coffee9: Coffee,
  "user-plus": UserPlus,
  "check-circle": CheckCircle2,
  search: Search,
  mail: Mail,
  globe: Globe,
  message: MessageCircle,
  file: FileText,
  alert: ShieldAlert,
  "qr-code": QrCode,
  "message-circle": MessageCircle,
  sparkles: Sparkles,
  settings: Settings,
  minus: Minus,
  plus: Plus,
  x: X,
  "arrow-right": ArrowRight,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  info: Info,
  "circle-alert": CircleAlert,
  pencil: Pencil,
  wifi: Wifi,
  "cloud-off": CloudOff,
  lock: Lock,
  "trash-2": Trash2,
  "log-out": LogOut,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  image: Image,
  "triangle-alert": TriangleAlert,
  "battery-full": BatteryFull,
};

export default function Icon({ name, size = 22, className = "", stroke = "currentColor", strokeWidth = 1.75 }: { name: string; size?: number; className?: string; stroke?: string; strokeWidth?: number }) {
  const C = MAP[name] ?? Coffee;
  return <C size={size} color={stroke} strokeWidth={strokeWidth} className={`shrink-0 ${className}`} aria-hidden />;
}
